name: Deploy to Cloudways

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 141.164.61.123
          username: master_byqgfvytgg
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/master/applications/opwjxoqnte/public_html
            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:pixxie999/brainplayzone.git
              git fetch origin main
              git reset --hard origin/main
            else
              git pull origin main
            fi
